apiVersion: kustomize.toolkit.fluxcd.io/v1                                                                          │
│                                                                                                                   │
kind: Kustomization                                                                                                 │
│                                                                                                                   │
metadata:                                                                                                           │
│                                                                                                                   │
  name: app                                                                                                 │       │
  namespace: flux-system                                                                                            │
│                                                                                                                   │
spec:                                                                                                               │
│                                                                                                                   │
  interval: 1m0s                                                                                                   ││
  path: ./app/Stage                                                                                            │    │
  prune: true                                                                                                       │
  retryInterval: 1m                                                                                                 │
  timeout: 5m  │                                                                                                    │
  sourceRef:                                                                                                        │
                                                                                                                    │
    kind: GitRepository                                                                                             │
                                                                                                                    │
    name: flux-system  
